#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Demo\StatsD\Command\RandomMetricsCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new RandomMetricsCommand());

$application->run();
